### ISSUE TITLE
bug on "chain" keyword

### ISSUE THREAD

**Issue by jehongjeon27** [whitedev7773/NDI#1]
Unipad autoplay has 2 keyword type, Full keyword and Shorten keyword.
chain 1 -> c 1 (change Chain Number to "1")
on 1 1 -> o 1 1 (Press Down on button "1 1")
off 1 1 -> f 1 1 (Press Up on button "1 1")
delay 100 -> d 100 (delay for "100"ms)
touch 1 1 -> t 1 1 (Press Down and Up on button "1 1")

If there is "chain 1" on input text, the output text stops on line at "chain" keyword is on.
![NDI 1 0 bug](https://user-images.githubusercontent.com/43852416/215329859-fc73fbb5-ad46-4a49-b0ea-fb8fb9b0b310.png)

**Comment by whitedev7773** [comment]
두 키워드 모두 대응하도록 수정하였으며 1.0.1 버전에서 수정되었습니다.
Fixed On v1.0.1.
